
DEF_ERROR(OK, "Everything is ok!")
DEF_ERROR(BAD_POINTER_TREE, "Bad pointer of tree was passed in function")
DEF_ERROR(BAD_POINTER_NODE, "Bad pointer of node was passed in function")
DEF_ERROR(BAD_CALLOC, "Error in calloc when create new node")
DEF_ERROR(BAD_OPEN_FILE, "Error in openning file")
DEF_ERROR(BAD_CLOSE_FILE, "Error in closing file")
DEF_ERROR(ROOT_NULL, "Root of tree became null")
DEF_ERROR(BAD_VALUE_OF_DATA, "The value of data is bad")
DEF_ERROR(LOOP_IN_TREE, "Find loop in tree")
DEF_ERROR(TREE_SEARCH_NOT_DONE, "Error in recursive tree searching")
